[package]
name = "vertex"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy.workspace = true
bytes.workspace = true
libp2p.workspace = true
quick-protobuf.workspace = true
quick-protobuf-codec.workspace = true
asynchronous-codec.workspace = true
futures.workspace = true
tokio.workspace = true
rand.workspace = true
thiserror.workspace = true
unsigned-varint.workspace = true
vertex-network-primitives-traits.workspace = true
vertex-network-primitives.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
pb-rs = "0.9.1"
walkdir = "2.5.0"
