[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.84"
license = "AGPL-3.0"
homepage = "https://nullisyxz.github.io/vertex"
repository = "https://nullisxyz.github.io/vertex"

[workspace]
members = [
    # "crates/file",
    # "crates/manifest",
    # "crates/postage",
    # "crates/logging",
    # "bin/waku-swarm-relay",
    # "bin/swarm-tools",
    # "bin/wasm-playground",
    # "bin/swarm-wasm-lib",
    "bin/vertex",
    "crates/network-primitives",
    "crates/network-primitives-traits",
    "crates/network/handshake",
    "crates/primitives",
    "crates/primitives-traits",
    # "crates/storage",
]
# default-members = [
#     "bin/vertex",
#     "bin/waku-swarm-relay",
# ]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.lints]
rust.unreachable_pub = "warn"

[workspace.dependencies]
## nectar
nectar-primitives = { path = "crates/primitives", features = ["arbitrary"] }
nectar-primitives-traits = { path = "crates/primitives-traits" }

## vertex
# primitives
vertex-network-primitives = { path = "crates/network-primitives" }
vertex-network-primitives-traits = { path = "crates/network-primitives-traits" }

# network protocols
vertex-network-handshake = { path = "crates/network/handshake" }

## alloy
alloy = { version = "0.11", features = [
    "arbitrary",
    "eips",
    "full",
    "hyper",
    "json-rpc",
    "node-bindings",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-keystore",
    "signer-mnemonic",
] }
alloy-chains = { version = "0.1.58", default-features = false }

## libp2p
libp2p = { version = "0.55.0", features = ["tokio", "tcp", "noise", "yamux", "dns", "macros", "ecdsa", "identify", "upnp", "autonat", "ping"] }

## misc
clap = { version = "4.5.23", features = ["derive", "env"] }
# getrandom = "0.2"
rand = "0.8"
thiserror = "2.0.4"

## tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "ansi",
    "fmt",
    "std",
    "json",
    "time",
] }

bytes = "1.9.0"

## p2p
libp2p = { version = "0.55.0", features = ["tokio", "noise", "tcp", "yamux", "dns", "macros", "ecdsa", "identify", "upnp", "autonat", "ping"] }
quick-protobuf = "0.8.0"
quick-protobuf-codec = "0.3.1"
asynchronous-codec = "0.7.0"

## tokio
# tokio-stream = "0.1.17"
tokio = { version = "1.42.0", default-features = false, features = [
    "macros",
    "rt",
] }
# tokio-util = { version = "0.7.13", features = ["codec"] }

## async
futures = "0.3"

## wasm
# wasm-bindgen = "0.2.97"
# wasm-bindgen-futures = "0.4.47"
# wasm-bindgen-test = "0.3.47"
# js-sys = "0.3.74"

# dotenv = "0.15.0"
# reqwest = { version = "0.12.9", features = ["json"] }
anyhow = "1.0.94"

serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "3", default-features = false, features = ["macros"] }


## testing
arbitrary = "1.3"
assert_matches = "1.5.0"
criterion = { package = "codspeed-criterion-compat", version = "2.7" }
# pprof = "0.14"
proptest = "1.4"
proptest-arbitrary-interop = "0.1"
proptest-derive = "0.5"
# test-fuzz = "6"
